apiVersion: apps/v1
kind: Deployment
metadata:
  name: message
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message
  template:
    metadata:
      labels:                    
        app: messsage
    spec:                       
      containers:
      - name: message
        ports:
          - containerPort: 8080